NordicDoorSuggestionSystem/Controllers/ProfilePageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using NordicDoorSuggestionSystem.Entities;
using NordicDoorSuggestionSystem.Repositories;
using System.Data;
using NordicDoorSuggestionSystem.DataAccess;
using NordicDoorSuggestionSystem.Models.Employees;
using NordicDoorSuggestionSystem.Extensions;
using System.Drawing;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NordicDoorSuggestionSystem.Controllers
{
    public class ProfilePageController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly DataContext _context;
        private readonly IEmployeeRepository _employeeRepository;

        public ProfilePageController(UserManager<User> userManager, DataContext context, IEmployeeRepository employeeRepository)
        {
            _userManager = userManager;
            _context = context;
            _employeeRepository = employeeRepository;
        }

        // GET: /<controller>/
        [Authorize(Roles = "Administrator,Team Leder,Standard Bruker")]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);            
            ProfileViewModel vm = new ProfileViewModel();
            if (currentUser == null)
            {
                return NotFound();
            }
            var employee = _employeeRepository.GetEmployeeByNumber(currentUser.EmployeeNumber);
            vm.EmployeeNumber = currentUser.EmployeeNumber;
            vm.FirstName = currentUser.FirstName;
            vm.LastName = currentUser.LastName;
            vm.Role = currentUser.Role;
            vm.TeamID = employee.TeamID;
            var teamname = _context.Team.Where(e => e.TeamID.Equals(employee.TeamID)).Select(e => e.TeamName).FirstOrDefault();
            vm.TeamName = teamname;
            vm.CreatedSuggestions = employee.CreatedSuggestions;
            vm.ProfilePicture = employee.ProfilePicture; 
            var created = _context.Employees.Where(e => e.EmployeeNumber.Equals(vm.EmployeeNumber)).Select(e => e.CreatedSuggestions).FirstOrDefault();
            vm.CreatedSuggestions = created;
            var completed = _context.Employees.Where(e => e.EmployeeNumber.Equals(vm.EmployeeNumber)).Select(e => e.CompletedSuggestions).FirstOrDefault();
            vm.CompletedSuggestions = completed;

            return View(vm);
        }

        // GET: /<controller>/
        [Authorize(Roles = "Administrator,Team Leder,Standard Bruker")]
        public IActionResult Statistic()
        {
            return View();
        }

        //byte[] picture ???
        [Authorize(Roles = "Administrator,Team Leder,Standard Bruker")]
        [HttpPost]
        public async Task<IActionResult> UploadProfilePicture(ProfileViewModel profilevm)
        {
            var formFile = FormFileExtensions.GetBytes(profilevm.NewProfilePicture);

            var employee = new Employee
            {
                EmployeeNumber = profilevm.EmployeeNumber,
                FirstName = profilevm.FirstName,
                LastName = profilevm.LastName,
                Role = profilevm.Role,
                TeamID = profilevm.TeamID,
                ProfilePicture = formFile,
                CompletedSuggestions = profilevm.CompletedSuggestions,
                CreatedSuggestions = profilevm.CreatedSuggestions
            };
            _employeeRepository.Update(employee);

            return RedirectToAction("Index");
        }
    }
}

NordicDoorSuggestionSystem/Views/ProfilePage/Index.cshtml
@model NordicDoorSuggestionSystem.Models.Employees.ProfileViewModel

@{
    ViewBag.Title = "NSS | Profil";
    Layout = "~/Views/Shared/_ProfileLayout.cshtml";
}


<center>
    <div id="cardContainer" class="cardContainer">
        <div class="card">
            <div class="cardPicture">
                @if (Model.ProfilePicture != null)
                {
                     <img style="width:125px; height: 125px;"src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(Model.ProfilePicture))" />
                }
                else  {<i class="fa fa-user" style="font-size:75px; color: grey;"></i>}
          
            </div>
            <div class="cardHeader">
                
                <label>@Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</label>
            </div>
            <div class="cardProfileInfo">
                <p>Ansatt nr: <label>@Html.DisplayFor(model => model.EmployeeNumber)</label> </p>
                <p>Rolle: <label>@Html.DisplayFor(model => model.Role)</label> </p>
                <p>Team: <label>@Html.DisplayFor(model => model.TeamName)</label> </p>
            </div>
            <div>
                <form asp-controller="ProfilePage" asp-action="UploadProfilePicture" method="post" enctype="multipart/form-data">
                    <input asp-for="EmployeeNumber" type="hidden"  />
                    <input asp-for="FirstName" type="hidden"  />
                    <input asp-for="LastName" type="hidden"  />
                    <input asp-for="TeamID" type="hidden"  />
                    <input asp-for="Role" type="hidden"  />
                    <input asp-for="NewProfilePicture" type="file" onchange="filecheck(this)" />
                    <input type="Submit" value="Submit" />
                </form>
 
            </div>
            <div class="showMyStats">
                <center>
                    <div class="stats">
                          <div class="present">
                            <div class="lid">
                                <span></span>
                            </div>
                        <div class="promo">
                            <p>DU HAR</p>
                            <h2>@Html.DisplayFor(model => model.CreatedSuggestions) Forslag!</h2>
                        </div>
                        <div class="box">
                            <span></span>
                            <span></span>
                        </div>
                    </div>
                    </div>
                </center>
            </div>
        </div>
    </div>
</center>