NordicDoorSuggestionSystem/Models/Account/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace NordicDoorSuggestionSystem.Models.Account;

public class LoginViewModel
{
    [Required]
    [DataType(DataType.Text)]
    [Display (Name = "Ansatt nummer")]
    public string EmployeeNumber { get; set; }

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; }

    [Display(Name = "Remember me?")]
    public bool RememberMe { get; set; }
}

NordicDoorSuggestionSystem/Controllers/HomeController.cs
using NordicDoorSuggestionSystem.DataAccess;
using NordicDoorSuggestionSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace NordicDoorSuggestionSystem.Controllers
{
    // [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize(Roles ="Administrator,Team Leder,Standard Bruker")]
        [HttpGet]
        public IActionResult Index()
        {
            return View("Index");
        }


    }
}

NordicDoorSuggestionSystem/Controllers/SuggestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NordicDoorSuggestionSystem.DataAccess;
using NordicDoorSuggestionSystem.Entities;
using NordicDoorSuggestionSystem.Models;
using Microsoft.AspNetCore.Identity;
using NordicDoorSuggestionSystem.Repositories;
using System.Data;
using System.Reflection;

namespace NordicDoorSuggestionSystem.Controllers
{
    //[Authorize]
    public class SuggestionController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IEmployeeRepository employeeRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly ISuggestionRepository _suggestionRepository;
        private readonly DataContext _context;
        private readonly ISqlConnector sqlConnector;


        public SuggestionController(
            UserManager<User> userManager,
            IEmployeeRepository employeeRepository,
            ISuggestionRepository suggestionRepository,
            ITeamRepository teamRepository,
            DataContext context, 
            ISqlConnector sqlConnector)



        {
            _userManager = userManager;
            _suggestionRepository = suggestionRepository;
            _context = context;
            _teamRepository = teamRepository;
            this.sqlConnector = sqlConnector;
            this.employeeRepository = employeeRepository;
            
        }

        // GET: Suggestion/Henter  ut Suggestions fra databasen i en liste + legger til søkefunksjon
        // The function is called Index and has the parameter (searchString)
        // First it makes a variabel with a list of the Suggestions
        // Then checks if the string(with the listed items) is Null or Empty.
        // Then it calls the QuerySuggestions() from the SR, with the parameter (searchString).

        [Authorize(Roles = "Administrator,Team Leder,Standard Bruker")]
        [HttpGet]
        public async Task<IActionResult> Index(string title)
        {
            var suggestions = new List<Suggestion>();

            if (title != null)
            {
                suggestions = await _suggestionRepository.QueryTitle(title);
            }
            else
            {
                suggestions = await _suggestionRepository.GetSuggestions();
            }


            var mySuggestions = new List<MySuggestionsViewModel>();
            for (var i = 0; i < suggestions.Count(); i++)
            {

                var responsibleEmployee = employeeRepository.GetEmployeeByNumber(suggestions[i].ResponsibleEmployee.Value);
                var suggestionMaker = employeeRepository.GetEmployeeByNumber(suggestions[i].EmployeeNumber);
                var suggestion = new MySuggestionsViewModel
                {
                    SuggestionID = suggestions[i].SuggestionID,
                    Title = suggestions[i].Title,
                    ResponsibleEmployee = responsibleEmployee.LastName + ", " + responsibleEmployee.FirstName,
                    Problem = suggestions[i].Problem,
                    Solution = suggestions[i].Solution,
                    Goal = suggestions[i].Goal,
                    Deadline = suggestions[i].Deadline,
                    Progress = suggestions[i].Progress,
                    Maker = suggestionMaker.LastName + ", " + suggestionMaker.FirstName,
                    TeamName = suggestions[i].TeamName
                };
                mySuggestions.Add(suggestion);
            }
            return View(mySuggestions);
        }

        // GET: MySuggestions/Henter brukerens suggestions.
        // This function gets the suggestion view and shows the users suggestions.
        // Will test when it is possible to LogIn
        [Authorize(Roles = "Administrator,Team Leder,Standard Bruker")]
        [HttpGet]
        public async Task<IActionResult> MySuggestions(string title)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var suggestions = new List<Suggestion>();

            if (title != null)
            {
                suggestions = await _suggestionRepository.QueryTitleOnResponsible(title, user.EmployeeNumber);
            }
            else
            {
                suggestions = await _suggestionRepository.QueryResponsible(user.EmployeeNumber);
            }
            
            var employee = employeeRepository.GetEmployeeByNumber(user.EmployeeNumber);
            var mySuggestions = new List<MySuggestionsViewModel>();
            for (var i = 0; i < suggestions.Count(); i++)
            {
                var suggestionMaker = employeeRepository.GetEmployeeByNumber(suggestions[i].EmployeeNumber);
                var suggestion = new MySuggestionsViewModel
                {
                    SuggestionID = suggestions[i].SuggestionID,
                    Title = suggestions[i].Title,
                    ResponsibleEmployee = employee.LastName + ", " + employee.FirstName,
                    Problem = suggestions[i].Problem,
                    Solution = suggestions[i].Solution,
                    Goal = suggestions[i].Goal,
                    Deadline = suggestions[i].Deadline,
                    Progress = suggestions[i].Progress,
                    Maker = suggestionMaker.LastName + ", " + suggestionMaker.FirstName,
                    TeamName = suggestions[i].TeamName
                };
                mySuggestions.Add(suggestion);
            }
            return View(mySuggestions);
        }

        [Authorize(Roles = "Administrator,Team Leder,Standard Bruker")]
        [HttpGet]
        public async Task<IActionResult> CreatedSuggestions(string title)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var suggestions = new List<Suggestion>();

            if (title != null)
            {
                suggestions = await _suggestionRepository.QueryTitleOnEmployee(title, user.EmployeeNumber);
            }
            else
            {
                suggestions = await _suggestionRepository.QueryEmployee(user.EmployeeNumber);
            }
            var employee = employeeRepository.GetEmployeeByNumber(user.EmployeeNumber);
            var mySuggestions = new List<MySuggestionsViewModel>();
            for (var i = 0; i < suggestions.Count(); i++)
            {
                var responsibleEmployee = employeeRepository.GetEmployeeByNumber(suggestions[i].ResponsibleEmployee.Value);
                var suggestion = new MySuggestionsViewModel
                {
                    SuggestionID = suggestions[i].SuggestionID,
                    Title = suggestions[i].Title,
                    ResponsibleEmployee = responsibleEmployee.LastName + ", " + responsibleEmployee.FirstName,
                    Problem = suggestions[i].Problem,
                    Solution = suggestions[i].Solution,
                    Goal = suggestions[i].Goal,
                    Deadline = suggestions[i].Deadline,
                    Progress = suggestions[i].Progress,
                    Maker = employee.LastName + ", " + employee.FirstName,
                    TeamName = suggestions[i].TeamName
                };
                mySuggestions.Add(suggestion);
            }
            return View(mySuggestions);
        }

        // GET: Suggestion/Details/Henter detaljer på et Forbedringsforslag
        // The function first checks if the ID = Null in the database.
        // Then gets the id of the selected suggestion and show the fields of the selected Suggestion.

        [HttpGet]
        [Authorize(Roles = "Administrator,Team Leder,Standard Bruker")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || await _suggestionRepository.GetSuggestions() == null)
            {
                return NotFound();
            }

            var suggestion = await _suggestionRepository.GetSuggestion(id);
            var responsible = employeeRepository.GetEmployeeByNumber(suggestion.ResponsibleEmployee.Value);
            if (suggestion == null)
            {
                return NotFound();
            }
            var vm = new SuggestionDetailViewModel
            {
                SuggestionID = suggestion.SuggestionID,
                Title = suggestion.Title,
                ResponsibleEmployee = responsible.LastName + ", " + responsible.FirstName,
                Problem = suggestion.Problem,
                Solution = suggestion.Solution,
                Goal = suggestion.Goal,
                Deadline = suggestion.Deadline,
                TeamName = suggestion.TeamName,
                Progress = suggestion.Progress
            };
            var Comments = _context.Comment.Where(d => d.SuggestionID.Equals(suggestion.SuggestionID)).ToList();
            vm.CommentsList = Comments;

            return View(vm);
        }

        // GET: Suggestion/Create

        [HttpGet]
        [Authorize(Roles = "Administrator,Team Leder,Standard Bruker")]
        public IActionResult Create()
        {
            var employees = _context.Employees.ToList();
            List<SelectListItem> responsibleItems = new List<SelectListItem>();
            for (var i = 0; i < employees.Count(); i++)
            {
                responsibleItems.Add(new SelectListItem()
                {
                    Value = employees[i].EmployeeNumber.ToString(),
                    Text = employees[i].LastName + ", " + employees[i].FirstName
                });
            }
            var createSgstnViewModel = new CreateSuggestionViewModel
            {
                ResponsibleList = responsibleItems                
            };
            return View(createSgstnViewModel);
        }

NordicDoorSuggestionSystem/Views/Home/Index.cshtml
@{
    Layout = null;
    ViewBag.Title = "NSS | Hjem";
 }
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
         <link rel="stylesheet" href="~/css/home.css" asp-append-version="true" />
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
<body>
    <style>
        .body{
                text-decoration: none;
                background-image: url('https://images.pexels.com/photos/260689/pexels-photo-260689.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2;');
                background-repeat: none;
                background-attachment: fixed;
                background-size: cover;
            }
    </style>
    
    <h1>NORDIC DOOR</h1>
    <a asp-controller="ProfilePage" asp-action="Index" class="fa fa-user-circle" aria-hidden="true"></a>
    <div class= "NavContainer0">
        <ul>
            <li class = "NavLink">
                <a class="nav-link text-dark" asp-area="" asp-controller="Suggestion" asp-action="Create">Nytt Forslag</a>
                <i class="fa fa-plus-square-o" aria-hidden="true"></i>
            </li>
        </ul>
    </div>
    <div class= "NavContainer">
        <ul>
            <li class = "NavLink">
                <a class="nav-link text-dark" asp-area="" asp-controller="Suggestion" asp-action="MySuggestions">Mine forslag</a>
                <i class="fa fa-user" aria-hidden="true"></i>
            </li>
        </ul>
    </div>
    <div class= "NavContainer1">
        <ul>
            <li class = "NavLink">
                <a class="nav-link text-dark" asp-area="" asp-controller="Suggestion" asp-action="Index">Alle forslag</a>
                <i class="fa fa-server" aria-hidden="true"></i>
            </li>
        </ul>
    </div>
    <div class= "NavContainer3">
        <ul>
            <li class = "NavLink">

                <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="MittTeam">Mitt Team</a>
                <i class="fa fa-users" aria-hidden="true"></i>
            </li>
        </ul>
    </div>
    <div class= "NavContainer2">
        <ul>
            <li class = "NavLink">
                <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="ShowStatisticsData">Statistikk</a>
                <i class="fa fa-bar-chart" aria-hidden="true"></i>
            </li>
        </ul>
    </div>
    <div class= "NavContainer4">
        <ul>
            <li class = "NavLink">
                <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="Index">Administration - admin only</a>
                <i class="" aria-hidden="true"></i>
            </li>
        </ul>
    </div>
</body>
</html>

NordicDoorSuggestionSystem/Views/Home/LogIn.cshtml
@{
    ViewData["Title"] = "NordicDoor Loginn";
}

<div class="text-center">
    <h1 class="display-4">LogIn</h1>
    <div>
        <form>
            <ul>
                <li>
                    <form action="" method="post">
                        <label for="Ansattnummer">Ansatt nummer</label><br>
                        <input type="text" id="Ansattnummer" name="Ansattnummer"><br>
                        <label for="password">Passord</label><br>
                        <input type="password" id="password" password="password"><br>
                        <input type="submit" value="Logg inn">
                    </form>
                </li>
            </ul>
        </form>
    </div>
</div>